### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by jihyungkim94** [prstrive/EPCDepth#1]
Epoch 0/20: N/A% 00/5650 || Elapsed Time: 0:00:00,ETA:  --:--:--,LR: -,Loss: ------
Traceback (most recent call last):
  File "main.py", line 55, in <module>
    model.main()
  File "/home/ji322906/EPCDepth/model.py", line 90, in main
    train_loss = self.train_epoch(epoch)
  File "/home/ji322906/EPCDepth/model.py", line 197, in train_epoch
    for batch, data in enumerate(self.train_loader):
  File "/home/ji322906/.conda/envs/jihyungkim94/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/home/ji322906/.conda/envs/jihyungkim94/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1199, in _next_data
    return self._process_data(data)
  File "/home/ji322906/.conda/envs/jihyungkim94/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
    data.reraise()
  File "/home/ji322906/.conda/envs/jihyungkim94/lib/python3.8/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/ji322906/.conda/envs/jihyungkim94/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/ji322906/.conda/envs/jihyungkim94/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ji322906/.conda/envs/jihyungkim94/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ji322906/EPCDepth/dataset/kitti_dataset.py", line 151, in __getitem__
    data["curr"] = self.transform(self.get_img(folder, frame_idx, side), is_flip, False, color_aug)
  File "/home/ji322906/EPCDepth/dataset/kitti_dataset.py", line 88, in get_img
    img_path = os.path.join(self.data_path, folder, "image_0{}/data".format(self.side_map[side]), "{:010d}{}".format(frame_idx, ".png"))
  File "/home/ji322906/.conda/envs/jihyungkim94/lib/python3.8/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

How do I fix it??

**Comment by prstrive** [comment]
Maybe you didn't declare the root directory “data_path” of the KITTI dataset? You can print the variables in the function "self.get_img" to check which variable is abnormal.

**Comment by jihyungkim94** [comment]
I unzipped the Kitti dataset into the directory of dataset. And I submitted to slurm job.
