### ISSUE TITLE
I sincerely congratulate you for publishing such an excellent article. After reading your article, I encountered a problem when running the code, I hope you can help to take a look

### ISSUE THREAD

**Issue by xiaoyudanaa** [prstrive/EPCDepth#3]
Traceback (most recent call last):
  File "main.py", line 55, in <module>
    model.main()
  File "/hpcfiles/users/hx/EPCDepth-main/model.py", line 89, in main
    train_loss = self.train_epoch(epoch)
  File "/hpcfiles/users/hx/EPCDepth-main/model.py", line 189, in train_epoch
    progressbar.Timer(), ",", progressbar.ETA(), ",", progressbar.Variable('LR', width=1), ",",
AttributeError: module 'progressbar' has no attribute 'Variable'

**Comment by prstrive** [comment]
You may need to install progressbar2 (pip install progressbar2) first.
